const state={puzzles:[],selectedTags:new Set(),search:"",difficulty:"all",hidePlayed:false,active:null,played:new Set(JSON.parse(localStorage.getItem("playedPuzzles")||"[]"))};
const $=id=>document.getElementById(id);
const els={list:$("puzzleList"),tags:$("tagFilters"),search:$("searchInput"),difficulty:$("difficultyFilter"),hidePlayed:$("hidePlayedToggle"),stats:$("stats"),random:$("randomBtn"),reset:$("resetPlayedBtn"),dialog:$("puzzleDialog"),close:$("closeDialog"),meta:$("dialogMeta"),title:$("dialogTitle"),dialogTags:$("dialogTags"),surface:$("dialogSurface"),answer:$("dialogAnswer"),notes:$("dialogNotes"),hostPanel:$("hostPanel"),reveal:$("revealBtn"),copy:$("copySurfaceBtn"),mark:$("markPlayedBtn"),toast:$("toast")};
function savePlayed(){localStorage.setItem("playedPuzzles",JSON.stringify([...state.played]))}
function toast(msg){els.toast.textContent=msg;els.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove("show"),1500)}
function stars(n){return "★".repeat(n)+"☆".repeat(5-n)}
function allTags(){return[...new Set(state.puzzles.flatMap(p=>p.tags))].sort((a,b)=>a.localeCompare(b,"zh-CN"))}
function filtered(){const q=state.search.trim().toLowerCase();return state.puzzles.filter(p=>{const tagOk=state.selectedTags.size===0||p.tags.some(t=>state.selectedTags.has(t));const diffOk=state.difficulty==="all"||String(p.difficulty)===state.difficulty;const playedOk=!state.hidePlayed||!state.played.has(p.id);const hay=`${p.title} ${p.surface} ${p.tags.join(" ")}`.toLowerCase();return tagOk&&diffOk&&playedOk&&(!q||hay.includes(q))})}
function renderTags(){els.tags.innerHTML="";for(const tag of allTags()){const b=document.createElement("button");b.className="chip"+(state.selectedTags.has(tag)?" is-active":"");b.textContent=tag;b.addEventListener("click",()=>{state.selectedTags.has(tag)?state.selectedTags.delete(tag):state.selectedTags.add(tag);render()});els.tags.appendChild(b)}}
function renderList(){const data=filtered();els.list.innerHTML="";if(!data.length)els.list.innerHTML='<div class="card"><p class="surface">没有符合条件的汤。换个标签试试。</p></div>';for(const p of data){const card=document.createElement("article");card.className="puzzle-card"+(state.played.has(p.id)?" is-played":"");card.tabIndex=0;card.innerHTML=`<div class="card-meta"><span>#${p.id} · ${stars(p.difficulty)}</span><span>${state.played.has(p.id)?"已玩":"未玩"}</span></div><h3>${p.title}</h3><p>${p.surface}</p><div class="chips chips--small">${p.tags.map(t=>`<span class="chip">${t}</span>`).join("")}</div>`;card.addEventListener("click",()=>openPuzzle(p));card.addEventListener("keydown",e=>{if(e.key==="Enter")openPuzzle(p)});els.list.appendChild(card)}els.stats.innerHTML=`共 ${state.puzzles.length} 题<br>当前显示 ${data.length} 题<br>已玩 ${state.played.size} 题`}
function render(){renderTags();renderList()}
function openPuzzle(p){state.active=p;els.meta.textContent=`#${p.id} · 难度 ${stars(p.difficulty)} · ${p.source}`;els.title.textContent=p.title;els.dialogTags.innerHTML=p.tags.map(t=>`<span class="chip">${t}</span>`).join("");els.surface.textContent=p.surface;els.answer.textContent=p.answer;els.notes.innerHTML=p.hostNotes.map(n=>`<li>${n}</li>`).join("");els.hostPanel.hidden=true;els.reveal.textContent="显示主持人信息";els.mark.textContent=state.played.has(p.id)?"取消已玩":"标记已玩";els.dialog.showModal()}
function randomPuzzle(){const candidates=filtered().filter(p=>!state.played.has(p.id));const pool=candidates.length?candidates:filtered();if(!pool.length)return toast("没有可抽的题");openPuzzle(pool[Math.floor(Math.random()*pool.length)])}
els.search.addEventListener("input",e=>{state.search=e.target.value;renderList()});els.difficulty.addEventListener("change",e=>{state.difficulty=e.target.value;renderList()});els.hidePlayed.addEventListener("change",e=>{state.hidePlayed=e.target.checked;renderList()});els.random.addEventListener("click",randomPuzzle);els.reset.addEventListener("click",()=>{state.played.clear();savePlayed();renderList();toast("已清空")});els.close.addEventListener("click",()=>els.dialog.close());els.dialog.addEventListener("click",e=>{if(e.target===els.dialog)els.dialog.close()});els.reveal.addEventListener("click",()=>{els.hostPanel.hidden=!els.hostPanel.hidden;els.reveal.textContent=els.hostPanel.hidden?"显示主持人信息":"隐藏主持人信息"});els.copy.addEventListener("click",async()=>{if(!state.active)return;await navigator.clipboard.writeText(`《${state.active.title}》\n\n${state.active.surface}`);toast("汤面已复制")});els.mark.addEventListener("click",()=>{if(!state.active)return;state.played.has(state.active.id)?state.played.delete(state.active.id):state.played.add(state.active.id);savePlayed();els.mark.textContent=state.played.has(state.active.id)?"取消已玩":"标记已玩";renderList();toast(state.played.has(state.active.id)?"已标记":"已取消")});
fetch("puzzles.json").then(r=>r.json()).then(data=>{state.puzzles=data;render()}).catch(err=>{els.list.innerHTML=`<div class="card">题库加载失败：${err.message}</div>`});
